# Generated by Django 5.1.3 on 2024-11-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('birthdate', models.DateField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=128)),
                ('interests', models.CharField(max_length=150)),
                ('profilepicture', models.ImageField(blank=True, null=True, upload_to='uploads/profile_pictures/')),
            ],
        ),
    ]
