# Generated by Django 5.0.4 on 2024-11-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission'),
        ),
    ]
