# Generated by Django 5.0.4 on 2024-11-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_event_event_date_remove_event_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='İstanbul', max_length=100),
        ),
    ]
