# Generated by Django 5.0.4 on 2024-11-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinterests',
            name='interests',
        ),
        migrations.AddField(
            model_name='userinterests',
            name='interests',
            field=models.ManyToManyField(to='users.interest'),
        ),
    ]
