# Generated by Django 5.0.4 on 2024-11-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
