# Generated by Django 5.0.4 on 2024-11-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_notification_content_notification_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='score',
            field=models.IntegerField(default=20),
        ),
    ]
