# Generated by Django 5.0.4 on 2024-11-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_event_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='score',
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=20),
        ),
    ]
